// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD0
typedef void (*UniffiCallbackInterfaceConnectionStorageMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD1
typedef void (*UniffiCallbackInterfaceConnectionStorageMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD2
typedef void (*UniffiCallbackInterfaceConnectionStorageMethod2)(uint64_t, RustBuffer, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CONNECTION_STORAGE_METHOD3
typedef void (*UniffiCallbackInterfaceConnectionStorageMethod3)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CREDENTIAL_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CREDENTIAL_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceCredentialProviderMethod0)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CREDENTIAL_PROVIDER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CREDENTIAL_PROVIDER_METHOD1
typedef void (*UniffiCallbackInterfaceCredentialProviderMethod1)(uint64_t, RustBuffer, RustBuffer, int8_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD0
typedef void (*UniffiCallbackInterfaceEventHandlerMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_IDENTITY_STORAGE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_IDENTITY_STORAGE_METHOD0
typedef void (*UniffiCallbackInterfaceIdentityStorageMethod0)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_IDENTITY_STORAGE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_IDENTITY_STORAGE_METHOD1
typedef void (*UniffiCallbackInterfaceIdentityStorageMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CONNECTION_STORAGE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CONNECTION_STORAGE
typedef struct UniffiVTableCallbackInterfaceConnectionStorage {
    UniffiCallbackInterfaceConnectionStorageMethod0 _Nonnull get;
    UniffiCallbackInterfaceConnectionStorageMethod1 _Nonnull save;
    UniffiCallbackInterfaceConnectionStorageMethod2 _Nonnull update;
    UniffiCallbackInterfaceConnectionStorageMethod3 _Nonnull list;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceConnectionStorage;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CREDENTIAL_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CREDENTIAL_PROVIDER
typedef struct UniffiVTableCallbackInterfaceCredentialProvider {
    UniffiCallbackInterfaceCredentialProviderMethod0 _Nonnull handleCredentialRequest;
    UniffiCallbackInterfaceCredentialProviderMethod1 _Nonnull verifyFingerprint;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceCredentialProvider;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_HANDLER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_HANDLER
typedef struct UniffiVTableCallbackInterfaceEventHandler {
    UniffiCallbackInterfaceEventHandlerMethod0 _Nonnull onEvent;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceEventHandler;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_IDENTITY_STORAGE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_IDENTITY_STORAGE
typedef struct UniffiVTableCallbackInterfaceIdentityStorage {
    UniffiCallbackInterfaceIdentityStorageMethod0 _Nonnull loadIdentity;
    UniffiCallbackInterfaceIdentityStorageMethod1 _Nonnull saveIdentity;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceIdentityStorage;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CLONE_REMOTEACCESSCLIENT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CLONE_REMOTEACCESSCLIENT
void*_Nonnull uniffi_ap_uniffi_fn_clone_remoteaccessclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_FREE_REMOTEACCESSCLIENT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_FREE_REMOTEACCESSCLIENT
void uniffi_ap_uniffi_fn_free_remoteaccessclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CONSTRUCTOR_REMOTEACCESSCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CONSTRUCTOR_REMOTEACCESSCLIENT_NEW
void*_Nonnull uniffi_ap_uniffi_fn_constructor_remoteaccessclient_new(RustBuffer proxy_url, uint64_t identity_storage, uint64_t connection_storage, RustBuffer event_handler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_CLOSE
void uniffi_ap_uniffi_fn_method_remoteaccessclient_close(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_CONNECT
void uniffi_ap_uniffi_fn_method_remoteaccessclient_connect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_LIST_CONNECTIONS
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_LIST_CONNECTIONS
RustBuffer uniffi_ap_uniffi_fn_method_remoteaccessclient_list_connections(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_LOAD_EXISTING_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_LOAD_EXISTING_CONNECTION
void uniffi_ap_uniffi_fn_method_remoteaccessclient_load_existing_connection(void*_Nonnull ptr, RustBuffer fingerprint_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_HANDSHAKE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_HANDSHAKE
RustBuffer uniffi_ap_uniffi_fn_method_remoteaccessclient_pair_with_handshake(void*_Nonnull ptr, RustBuffer code, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_PSK
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_PSK
void uniffi_ap_uniffi_fn_method_remoteaccessclient_pair_with_psk(void*_Nonnull ptr, RustBuffer psk_token, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_REQUEST_CREDENTIAL
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_REMOTEACCESSCLIENT_REQUEST_CREDENTIAL
RustBuffer uniffi_ap_uniffi_fn_method_remoteaccessclient_request_credential(void*_Nonnull ptr, RustBuffer domain, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CLONE_USERACCESSCLIENT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CLONE_USERACCESSCLIENT
void*_Nonnull uniffi_ap_uniffi_fn_clone_useraccessclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_FREE_USERACCESSCLIENT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_FREE_USERACCESSCLIENT
void uniffi_ap_uniffi_fn_free_useraccessclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CONSTRUCTOR_USERACCESSCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_CONSTRUCTOR_USERACCESSCLIENT_NEW
void*_Nonnull uniffi_ap_uniffi_fn_constructor_useraccessclient_new(RustBuffer proxy_url, uint64_t identity_storage, uint64_t connection_storage, uint64_t handler, RustBuffer event_handler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_CLOSE
void uniffi_ap_uniffi_fn_method_useraccessclient_close(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_CONNECT
void uniffi_ap_uniffi_fn_method_useraccessclient_connect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_GET_PSK_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_GET_PSK_TOKEN
RustBuffer uniffi_ap_uniffi_fn_method_useraccessclient_get_psk_token(void*_Nonnull ptr, int8_t reusable, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_GET_RENDEZVOUS_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_METHOD_USERACCESSCLIENT_GET_RENDEZVOUS_TOKEN
RustBuffer uniffi_ap_uniffi_fn_method_useraccessclient_get_rendezvous_token(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_CONNECTIONSTORAGE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_CONNECTIONSTORAGE
void uniffi_ap_uniffi_fn_init_callback_vtable_connectionstorage(UniffiVTableCallbackInterfaceConnectionStorage* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_CREDENTIALPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_CREDENTIALPROVIDER
void uniffi_ap_uniffi_fn_init_callback_vtable_credentialprovider(UniffiVTableCallbackInterfaceCredentialProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_EVENTHANDLER
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_EVENTHANDLER
void uniffi_ap_uniffi_fn_init_callback_vtable_eventhandler(UniffiVTableCallbackInterfaceEventHandler* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_IDENTITYSTORAGE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_INIT_CALLBACK_VTABLE_IDENTITYSTORAGE
void uniffi_ap_uniffi_fn_init_callback_vtable_identitystorage(UniffiVTableCallbackInterfaceIdentityStorage* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_FUNC_LOOKS_LIKE_PSK_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_FN_FUNC_LOOKS_LIKE_PSK_TOKEN
int8_t uniffi_ap_uniffi_fn_func_looks_like_psk_token(RustBuffer token, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_ALLOC
RustBuffer ffi_ap_uniffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_ap_uniffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_FREE
void ffi_ap_uniffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUSTBUFFER_RESERVE
RustBuffer ffi_ap_uniffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U8
void ffi_ap_uniffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U8
void ffi_ap_uniffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U8
void ffi_ap_uniffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_ap_uniffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I8
void ffi_ap_uniffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I8
void ffi_ap_uniffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I8
void ffi_ap_uniffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_ap_uniffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U16
void ffi_ap_uniffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U16
void ffi_ap_uniffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U16
void ffi_ap_uniffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_ap_uniffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I16
void ffi_ap_uniffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I16
void ffi_ap_uniffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I16
void ffi_ap_uniffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_ap_uniffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U32
void ffi_ap_uniffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U32
void ffi_ap_uniffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U32
void ffi_ap_uniffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_ap_uniffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I32
void ffi_ap_uniffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I32
void ffi_ap_uniffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I32
void ffi_ap_uniffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_ap_uniffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_U64
void ffi_ap_uniffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_U64
void ffi_ap_uniffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_U64
void ffi_ap_uniffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_ap_uniffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_I64
void ffi_ap_uniffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_I64
void ffi_ap_uniffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_I64
void ffi_ap_uniffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_ap_uniffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_F32
void ffi_ap_uniffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_F32
void ffi_ap_uniffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_F32
void ffi_ap_uniffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_F32
float ffi_ap_uniffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_F64
void ffi_ap_uniffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_F64
void ffi_ap_uniffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_F64
void ffi_ap_uniffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_F64
double ffi_ap_uniffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_POINTER
void ffi_ap_uniffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_POINTER
void ffi_ap_uniffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_POINTER
void ffi_ap_uniffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_ap_uniffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_ap_uniffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_ap_uniffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_ap_uniffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_ap_uniffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_POLL_VOID
void ffi_ap_uniffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_CANCEL_VOID
void ffi_ap_uniffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_FREE_VOID
void ffi_ap_uniffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_ap_uniffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_FUNC_LOOKS_LIKE_PSK_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_FUNC_LOOKS_LIKE_PSK_TOKEN
uint16_t uniffi_ap_uniffi_checksum_func_looks_like_psk_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_CLOSE
uint16_t uniffi_ap_uniffi_checksum_method_remoteaccessclient_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_CONNECT
uint16_t uniffi_ap_uniffi_checksum_method_remoteaccessclient_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_LIST_CONNECTIONS
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_LIST_CONNECTIONS
uint16_t uniffi_ap_uniffi_checksum_method_remoteaccessclient_list_connections(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_LOAD_EXISTING_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_LOAD_EXISTING_CONNECTION
uint16_t uniffi_ap_uniffi_checksum_method_remoteaccessclient_load_existing_connection(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_HANDSHAKE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_HANDSHAKE
uint16_t uniffi_ap_uniffi_checksum_method_remoteaccessclient_pair_with_handshake(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_PSK
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_PAIR_WITH_PSK
uint16_t uniffi_ap_uniffi_checksum_method_remoteaccessclient_pair_with_psk(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_REQUEST_CREDENTIAL
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_REMOTEACCESSCLIENT_REQUEST_CREDENTIAL
uint16_t uniffi_ap_uniffi_checksum_method_remoteaccessclient_request_credential(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_CLOSE
uint16_t uniffi_ap_uniffi_checksum_method_useraccessclient_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_CONNECT
uint16_t uniffi_ap_uniffi_checksum_method_useraccessclient_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_GET_PSK_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_GET_PSK_TOKEN
uint16_t uniffi_ap_uniffi_checksum_method_useraccessclient_get_psk_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_GET_RENDEZVOUS_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_USERACCESSCLIENT_GET_RENDEZVOUS_TOKEN
uint16_t uniffi_ap_uniffi_checksum_method_useraccessclient_get_rendezvous_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_CONSTRUCTOR_REMOTEACCESSCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_CONSTRUCTOR_REMOTEACCESSCLIENT_NEW
uint16_t uniffi_ap_uniffi_checksum_constructor_remoteaccessclient_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_CONSTRUCTOR_USERACCESSCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_CONSTRUCTOR_USERACCESSCLIENT_NEW
uint16_t uniffi_ap_uniffi_checksum_constructor_useraccessclient_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_GET
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_GET
uint16_t uniffi_ap_uniffi_checksum_method_connectionstorage_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_SAVE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_SAVE
uint16_t uniffi_ap_uniffi_checksum_method_connectionstorage_save(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_UPDATE
uint16_t uniffi_ap_uniffi_checksum_method_connectionstorage_update(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_LIST
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CONNECTIONSTORAGE_LIST
uint16_t uniffi_ap_uniffi_checksum_method_connectionstorage_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CREDENTIALPROVIDER_HANDLE_CREDENTIAL_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CREDENTIALPROVIDER_HANDLE_CREDENTIAL_REQUEST
uint16_t uniffi_ap_uniffi_checksum_method_credentialprovider_handle_credential_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CREDENTIALPROVIDER_VERIFY_FINGERPRINT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_CREDENTIALPROVIDER_VERIFY_FINGERPRINT
uint16_t uniffi_ap_uniffi_checksum_method_credentialprovider_verify_fingerprint(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_EVENTHANDLER_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_EVENTHANDLER_ON_EVENT
uint16_t uniffi_ap_uniffi_checksum_method_eventhandler_on_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_IDENTITYSTORAGE_LOAD_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_IDENTITYSTORAGE_LOAD_IDENTITY
uint16_t uniffi_ap_uniffi_checksum_method_identitystorage_load_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_IDENTITYSTORAGE_SAVE_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_AP_UNIFFI_CHECKSUM_METHOD_IDENTITYSTORAGE_SAVE_IDENTITY
uint16_t uniffi_ap_uniffi_checksum_method_identitystorage_save_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_AP_UNIFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_AP_UNIFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_ap_uniffi_uniffi_contract_version(void
    
);
#endif

