// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ap_uniffiFFI)
import ap_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ap_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ap_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A remote-access client for requesting credentials from a trusted peer.
 *
 * Thin wrapper around `ap_client::RemoteClient` exposing individual pairing
 * methods — connection mode orchestration (PSK vs rendezvous vs cached)
 * belongs in the consumer, not here.
 *
 * Implements `Drop` to ensure the underlying connection is closed if the
 * caller forgets to call `close()`.
 */
public protocol RemoteAccessClientProtocol : AnyObject {
    
    /**
     * Close the connection and release resources.
     */
    func close() 
    
    /**
     * Connect to the proxy server and authenticate.
     *
     * After this, call one of the pairing methods to establish a secure channel:
     * `pair_with_handshake()`, `pair_with_psk()`, or `load_existing_connection()`.
     */
    func connect() throws 
    
    /**
     * List all cached connections.
     */
    func listConnections()  -> [FfiConnectionInfo]
    
    /**
     * Reconnect to a previously paired device using a cached connection.
     *
     * * `fingerprint_hex` — Hex-encoded identity fingerprint of the remote peer.
     */
    func loadExistingConnection(fingerprintHex: String) throws 
    
    /**
     * Pair with a new device using a rendezvous code.
     *
     * * `code` — Rendezvous code (e.g. "ABC-DEF-GHI").
     *
     * Returns the 6-char handshake fingerprint as a hex string for out-of-band
     * verification. No fingerprint verification is performed (headless mode).
     */
    func pairWithHandshake(code: String) throws  -> String
    
    /**
     * Pair with a new device using a PSK token.
     *
     * * `psk_token` — PSK token string (`<64-hex-psk>_<64-hex-fingerprint>`).
     */
    func pairWithPsk(pskToken: String) throws 
    
    /**
     * Request a credential for a domain.
     *
     * * `domain` — The domain to look up (e.g. "example.com").
     */
    func requestCredential(domain: String) throws  -> FfiCredentialData
    
}

/**
 * A remote-access client for requesting credentials from a trusted peer.
 *
 * Thin wrapper around `ap_client::RemoteClient` exposing individual pairing
 * methods — connection mode orchestration (PSK vs rendezvous vs cached)
 * belongs in the consumer, not here.
 *
 * Implements `Drop` to ensure the underlying connection is closed if the
 * caller forgets to call `close()`.
 */
open class RemoteAccessClient:
    RemoteAccessClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ap_uniffi_fn_clone_remoteaccessclient(self.pointer, $0) }
    }
    /**
     * Create a new RemoteAccessClient.
     *
     * * `proxy_url` — WebSocket URL of the proxy server (e.g. "ws://localhost:8080").
     * * `identity_storage` — Callback for persistent identity keypair storage.
     * * `connection_storage` — Callback for persistent connection cache storage.
     * * `event_handler` — Optional callback for receiving status notifications.
     */
public convenience init(proxyUrl: String, identityStorage: IdentityStorage, connectionStorage: ConnectionStorage, eventHandler: EventHandler?)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_constructor_remoteaccessclient_new(
        FfiConverterString.lower(proxyUrl),
        FfiConverterCallbackInterfaceIdentityStorage.lower(identityStorage),
        FfiConverterCallbackInterfaceConnectionStorage.lower(connectionStorage),
        FfiConverterOptionCallbackInterfaceEventHandler.lower(eventHandler),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ap_uniffi_fn_free_remoteaccessclient(pointer, $0) }
    }

    

    
    /**
     * Close the connection and release resources.
     */
open func close() {try! rustCall() {
    uniffi_ap_uniffi_fn_method_remoteaccessclient_close(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Connect to the proxy server and authenticate.
     *
     * After this, call one of the pairing methods to establish a secure channel:
     * `pair_with_handshake()`, `pair_with_psk()`, or `load_existing_connection()`.
     */
open func connect()throws  {try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_remoteaccessclient_connect(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * List all cached connections.
     */
open func listConnections() -> [FfiConnectionInfo] {
    return try!  FfiConverterSequenceTypeFfiConnectionInfo.lift(try! rustCall() {
    uniffi_ap_uniffi_fn_method_remoteaccessclient_list_connections(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Reconnect to a previously paired device using a cached connection.
     *
     * * `fingerprint_hex` — Hex-encoded identity fingerprint of the remote peer.
     */
open func loadExistingConnection(fingerprintHex: String)throws  {try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_remoteaccessclient_load_existing_connection(self.uniffiClonePointer(),
        FfiConverterString.lower(fingerprintHex),$0
    )
}
}
    
    /**
     * Pair with a new device using a rendezvous code.
     *
     * * `code` — Rendezvous code (e.g. "ABC-DEF-GHI").
     *
     * Returns the 6-char handshake fingerprint as a hex string for out-of-band
     * verification. No fingerprint verification is performed (headless mode).
     */
open func pairWithHandshake(code: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_remoteaccessclient_pair_with_handshake(self.uniffiClonePointer(),
        FfiConverterString.lower(code),$0
    )
})
}
    
    /**
     * Pair with a new device using a PSK token.
     *
     * * `psk_token` — PSK token string (`<64-hex-psk>_<64-hex-fingerprint>`).
     */
open func pairWithPsk(pskToken: String)throws  {try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_remoteaccessclient_pair_with_psk(self.uniffiClonePointer(),
        FfiConverterString.lower(pskToken),$0
    )
}
}
    
    /**
     * Request a credential for a domain.
     *
     * * `domain` — The domain to look up (e.g. "example.com").
     */
open func requestCredential(domain: String)throws  -> FfiCredentialData {
    return try  FfiConverterTypeFfiCredentialData.lift(try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_remoteaccessclient_request_credential(self.uniffiClonePointer(),
        FfiConverterString.lower(domain),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRemoteAccessClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = RemoteAccessClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> RemoteAccessClient {
        return RemoteAccessClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: RemoteAccessClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RemoteAccessClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: RemoteAccessClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemoteAccessClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> RemoteAccessClient {
    return try FfiConverterTypeRemoteAccessClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemoteAccessClient_lower(_ value: RemoteAccessClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeRemoteAccessClient.lower(value)
}




/**
 * A user-client (trusted device) that listens for incoming credential requests.
 *
 * Wraps `ap_client::UserClient` behind a synchronous FFI-safe API.
 * Credential requests and fingerprint verifications are dispatched to the
 * `CredentialProvider` callback supplied at construction.
 */
public protocol UserAccessClientProtocol : AnyObject {
    
    /**
     * Close the connection and release resources.
     */
    func close() 
    
    /**
     * Connect to the proxy server and start listening for incoming connections.
     *
     * Spawns a background event loop that dispatches credential requests and
     * fingerprint verifications to the `CredentialProvider` callback.
     */
    func connect() throws 
    
    /**
     * Generate a PSK token for pairing.
     *
     * * `reusable` — If true, the token can be used multiple times.
     *
     * Returns the PSK token string (`<64-hex-psk>_<64-hex-fingerprint>`).
     */
    func getPskToken(reusable: Bool) throws  -> String
    
    /**
     * Generate a rendezvous code for pairing.
     *
     * Returns the rendezvous code string (e.g. "ABC-DEF-GHI").
     */
    func getRendezvousToken() throws  -> String
    
}

/**
 * A user-client (trusted device) that listens for incoming credential requests.
 *
 * Wraps `ap_client::UserClient` behind a synchronous FFI-safe API.
 * Credential requests and fingerprint verifications are dispatched to the
 * `CredentialProvider` callback supplied at construction.
 */
open class UserAccessClient:
    UserAccessClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ap_uniffi_fn_clone_useraccessclient(self.pointer, $0) }
    }
    /**
     * Create a new UserAccessClient.
     *
     * * `proxy_url` — WebSocket URL of the proxy server.
     * * `identity_storage` — Callback for persistent identity keypair storage.
     * * `connection_storage` — Callback for persistent connection cache storage.
     * * `handler` — Callback for credential requests and fingerprint verification.
     * * `event_handler` — Optional callback for status notifications.
     */
public convenience init(proxyUrl: String, identityStorage: IdentityStorage, connectionStorage: ConnectionStorage, handler: CredentialProvider, eventHandler: EventHandler?)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_constructor_useraccessclient_new(
        FfiConverterString.lower(proxyUrl),
        FfiConverterCallbackInterfaceIdentityStorage.lower(identityStorage),
        FfiConverterCallbackInterfaceConnectionStorage.lower(connectionStorage),
        FfiConverterCallbackInterfaceCredentialProvider.lower(handler),
        FfiConverterOptionCallbackInterfaceEventHandler.lower(eventHandler),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ap_uniffi_fn_free_useraccessclient(pointer, $0) }
    }

    

    
    /**
     * Close the connection and release resources.
     */
open func close() {try! rustCall() {
    uniffi_ap_uniffi_fn_method_useraccessclient_close(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Connect to the proxy server and start listening for incoming connections.
     *
     * Spawns a background event loop that dispatches credential requests and
     * fingerprint verifications to the `CredentialProvider` callback.
     */
open func connect()throws  {try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_useraccessclient_connect(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Generate a PSK token for pairing.
     *
     * * `reusable` — If true, the token can be used multiple times.
     *
     * Returns the PSK token string (`<64-hex-psk>_<64-hex-fingerprint>`).
     */
open func getPskToken(reusable: Bool)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_useraccessclient_get_psk_token(self.uniffiClonePointer(),
        FfiConverterBool.lower(reusable),$0
    )
})
}
    
    /**
     * Generate a rendezvous code for pairing.
     *
     * Returns the rendezvous code string (e.g. "ABC-DEF-GHI").
     */
open func getRendezvousToken()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRemoteAccessError.lift) {
    uniffi_ap_uniffi_fn_method_useraccessclient_get_rendezvous_token(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserAccessClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = UserAccessClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> UserAccessClient {
        return UserAccessClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: UserAccessClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserAccessClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: UserAccessClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserAccessClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> UserAccessClient {
    return try FfiConverterTypeUserAccessClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserAccessClient_lower(_ value: UserAccessClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeUserAccessClient.lower(value)
}


/**
 * Information about a cached connection.
 */
public struct FfiConnectionInfo {
    /**
     * Hex-encoded identity fingerprint of the remote peer.
     */
    public var fingerprint: String
    /**
     * Optional human-readable name for the connection.
     */
    public var name: String?
    /**
     * Unix timestamp (seconds) when the connection was first cached.
     */
    public var cachedAt: UInt64
    /**
     * Unix timestamp (seconds) of the last successful connection.
     */
    public var lastConnectedAt: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded identity fingerprint of the remote peer.
         */fingerprint: String, 
        /**
         * Optional human-readable name for the connection.
         */name: String?, 
        /**
         * Unix timestamp (seconds) when the connection was first cached.
         */cachedAt: UInt64, 
        /**
         * Unix timestamp (seconds) of the last successful connection.
         */lastConnectedAt: UInt64) {
        self.fingerprint = fingerprint
        self.name = name
        self.cachedAt = cachedAt
        self.lastConnectedAt = lastConnectedAt
    }
}



extension FfiConnectionInfo: Equatable, Hashable {
    public static func ==(lhs: FfiConnectionInfo, rhs: FfiConnectionInfo) -> Bool {
        if lhs.fingerprint != rhs.fingerprint {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.cachedAt != rhs.cachedAt {
            return false
        }
        if lhs.lastConnectedAt != rhs.lastConnectedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fingerprint)
        hasher.combine(name)
        hasher.combine(cachedAt)
        hasher.combine(lastConnectedAt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiConnectionInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiConnectionInfo {
        return
            try FfiConnectionInfo(
                fingerprint: FfiConverterString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                cachedAt: FfiConverterUInt64.read(from: &buf), 
                lastConnectedAt: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiConnectionInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterUInt64.write(value.cachedAt, into: &buf)
        FfiConverterUInt64.write(value.lastConnectedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiConnectionInfo_lift(_ buf: RustBuffer) throws -> FfiConnectionInfo {
    return try FfiConverterTypeFfiConnectionInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiConnectionInfo_lower(_ value: FfiConnectionInfo) -> RustBuffer {
    return FfiConverterTypeFfiConnectionInfo.lower(value)
}


/**
 * Credential data returned from a remote access request.
 */
public struct FfiCredentialData {
    public var username: String?
    public var password: String?
    public var totp: String?
    public var uri: String?
    public var notes: String?
    public var credentialId: String?
    public var domain: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(username: String?, password: String?, totp: String?, uri: String?, notes: String?, credentialId: String?, domain: String?) {
        self.username = username
        self.password = password
        self.totp = totp
        self.uri = uri
        self.notes = notes
        self.credentialId = credentialId
        self.domain = domain
    }
}



extension FfiCredentialData: Equatable, Hashable {
    public static func ==(lhs: FfiCredentialData, rhs: FfiCredentialData) -> Bool {
        if lhs.username != rhs.username {
            return false
        }
        if lhs.password != rhs.password {
            return false
        }
        if lhs.totp != rhs.totp {
            return false
        }
        if lhs.uri != rhs.uri {
            return false
        }
        if lhs.notes != rhs.notes {
            return false
        }
        if lhs.credentialId != rhs.credentialId {
            return false
        }
        if lhs.domain != rhs.domain {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(username)
        hasher.combine(password)
        hasher.combine(totp)
        hasher.combine(uri)
        hasher.combine(notes)
        hasher.combine(credentialId)
        hasher.combine(domain)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCredentialData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCredentialData {
        return
            try FfiCredentialData(
                username: FfiConverterOptionString.read(from: &buf), 
                password: FfiConverterOptionString.read(from: &buf), 
                totp: FfiConverterOptionString.read(from: &buf), 
                uri: FfiConverterOptionString.read(from: &buf), 
                notes: FfiConverterOptionString.read(from: &buf), 
                credentialId: FfiConverterOptionString.read(from: &buf), 
                domain: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiCredentialData, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.username, into: &buf)
        FfiConverterOptionString.write(value.password, into: &buf)
        FfiConverterOptionString.write(value.totp, into: &buf)
        FfiConverterOptionString.write(value.uri, into: &buf)
        FfiConverterOptionString.write(value.notes, into: &buf)
        FfiConverterOptionString.write(value.credentialId, into: &buf)
        FfiConverterOptionString.write(value.domain, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCredentialData_lift(_ buf: RustBuffer) throws -> FfiCredentialData {
    return try FfiConverterTypeFfiCredentialData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCredentialData_lower(_ value: FfiCredentialData) -> RustBuffer {
    return FfiConverterTypeFfiCredentialData.lower(value)
}


/**
 * Storage record for a cached connection (FFI-safe).
 *
 * `transport_state` is opaque bytes — language bindings store and return them
 * as-is. No CBOR parsing is needed on the language side.
 */
public struct FfiStoredConnection {
    /**
     * Hex-encoded identity fingerprint of the remote peer.
     */
    public var fingerprint: String
    /**
     * Optional human-readable name for the connection.
     */
    public var name: String?
    /**
     * Unix timestamp (seconds) when the connection was first cached.
     */
    public var cachedAt: UInt64
    /**
     * Unix timestamp (seconds) of the last successful connection.
     */
    public var lastConnectedAt: UInt64
    /**
     * Opaque transport state bytes — store and return as-is.
     */
    public var transportState: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded identity fingerprint of the remote peer.
         */fingerprint: String, 
        /**
         * Optional human-readable name for the connection.
         */name: String?, 
        /**
         * Unix timestamp (seconds) when the connection was first cached.
         */cachedAt: UInt64, 
        /**
         * Unix timestamp (seconds) of the last successful connection.
         */lastConnectedAt: UInt64, 
        /**
         * Opaque transport state bytes — store and return as-is.
         */transportState: Data?) {
        self.fingerprint = fingerprint
        self.name = name
        self.cachedAt = cachedAt
        self.lastConnectedAt = lastConnectedAt
        self.transportState = transportState
    }
}



extension FfiStoredConnection: Equatable, Hashable {
    public static func ==(lhs: FfiStoredConnection, rhs: FfiStoredConnection) -> Bool {
        if lhs.fingerprint != rhs.fingerprint {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.cachedAt != rhs.cachedAt {
            return false
        }
        if lhs.lastConnectedAt != rhs.lastConnectedAt {
            return false
        }
        if lhs.transportState != rhs.transportState {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fingerprint)
        hasher.combine(name)
        hasher.combine(cachedAt)
        hasher.combine(lastConnectedAt)
        hasher.combine(transportState)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiStoredConnection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiStoredConnection {
        return
            try FfiStoredConnection(
                fingerprint: FfiConverterString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                cachedAt: FfiConverterUInt64.read(from: &buf), 
                lastConnectedAt: FfiConverterUInt64.read(from: &buf), 
                transportState: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiStoredConnection, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterUInt64.write(value.cachedAt, into: &buf)
        FfiConverterUInt64.write(value.lastConnectedAt, into: &buf)
        FfiConverterOptionData.write(value.transportState, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStoredConnection_lift(_ buf: RustBuffer) throws -> FfiStoredConnection {
    return try FfiConverterTypeFfiStoredConnection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStoredConnection_lower(_ value: FfiStoredConnection) -> RustBuffer {
    return FfiConverterTypeFfiStoredConnection.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Notification event from client event loops.
 *
 * Covers events from both `RemoteClient` and `UserClient` in a single
 * FFI-friendly enum. All fingerprints are hex-encoded strings.
 */

public enum FfiEvent {
    
    /**
     * Connecting to the proxy server.
     */
    case connecting
    /**
     * Successfully connected to the proxy.
     */
    case connected(fingerprint: String
    )
    /**
     * Started listening for incoming connections.
     */
    case listening
    /**
     * Noise handshake started.
     */
    case handshakeStart
    /**
     * Noise handshake progress.
     */
    case handshakeProgress(message: String
    )
    /**
     * Noise handshake complete.
     */
    case handshakeComplete
    /**
     * Handshake fingerprint for visual verification.
     */
    case handshakeFingerprint(fingerprint: String, identity: String?
    )
    /**
     * Fingerprint was verified and connection accepted.
     */
    case fingerprintVerified
    /**
     * Fingerprint was rejected.
     */
    case fingerprintRejected(reason: String
    )
    /**
     * Client is ready for credential operations.
     */
    case ready
    /**
     * Credential request was sent.
     */
    case credentialRequestSent(domain: String
    )
    /**
     * Credential was received.
     */
    case credentialReceived
    /**
     * Credential was approved and sent (UserClient).
     */
    case credentialApproved(domain: String?, credentialId: String?
    )
    /**
     * Credential was denied (UserClient).
     */
    case credentialDenied(domain: String?, credentialId: String?
    )
    /**
     * Reconnecting to an existing session.
     */
    case reconnectingToSession(fingerprint: String
    )
    /**
     * A known device reconnected — transport keys refreshed.
     */
    case sessionRefreshed(fingerprint: String
    )
    /**
     * Resolving a rendezvous code.
     */
    case rendezvousResolving(code: String
    )
    /**
     * Rendezvous code resolved to a fingerprint.
     */
    case rendezvousResolved(fingerprint: String
    )
    /**
     * Using PSK mode for connection.
     */
    case pskMode(fingerprint: String
    )
    /**
     * Client disconnected from proxy.
     */
    case disconnected(reason: String?
    )
    /**
     * Attempting to reconnect to proxy.
     */
    case reconnecting(attempt: UInt32
    )
    /**
     * Successfully reconnected to proxy.
     */
    case reconnected
    /**
     * An error occurred.
     */
    case error(message: String, context: String?
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEvent: FfiConverterRustBuffer {
    typealias SwiftType = FfiEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connecting
        
        case 2: return .connected(fingerprint: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .listening
        
        case 4: return .handshakeStart
        
        case 5: return .handshakeProgress(message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .handshakeComplete
        
        case 7: return .handshakeFingerprint(fingerprint: try FfiConverterString.read(from: &buf), identity: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 8: return .fingerprintVerified
        
        case 9: return .fingerprintRejected(reason: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .ready
        
        case 11: return .credentialRequestSent(domain: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .credentialReceived
        
        case 13: return .credentialApproved(domain: try FfiConverterOptionString.read(from: &buf), credentialId: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 14: return .credentialDenied(domain: try FfiConverterOptionString.read(from: &buf), credentialId: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 15: return .reconnectingToSession(fingerprint: try FfiConverterString.read(from: &buf)
        )
        
        case 16: return .sessionRefreshed(fingerprint: try FfiConverterString.read(from: &buf)
        )
        
        case 17: return .rendezvousResolving(code: try FfiConverterString.read(from: &buf)
        )
        
        case 18: return .rendezvousResolved(fingerprint: try FfiConverterString.read(from: &buf)
        )
        
        case 19: return .pskMode(fingerprint: try FfiConverterString.read(from: &buf)
        )
        
        case 20: return .disconnected(reason: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 21: return .reconnecting(attempt: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 22: return .reconnected
        
        case 23: return .error(message: try FfiConverterString.read(from: &buf), context: try FfiConverterOptionString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connecting:
            writeInt(&buf, Int32(1))
        
        
        case let .connected(fingerprint):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(fingerprint, into: &buf)
            
        
        case .listening:
            writeInt(&buf, Int32(3))
        
        
        case .handshakeStart:
            writeInt(&buf, Int32(4))
        
        
        case let .handshakeProgress(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case .handshakeComplete:
            writeInt(&buf, Int32(6))
        
        
        case let .handshakeFingerprint(fingerprint,identity):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(fingerprint, into: &buf)
            FfiConverterOptionString.write(identity, into: &buf)
            
        
        case .fingerprintVerified:
            writeInt(&buf, Int32(8))
        
        
        case let .fingerprintRejected(reason):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .ready:
            writeInt(&buf, Int32(10))
        
        
        case let .credentialRequestSent(domain):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(domain, into: &buf)
            
        
        case .credentialReceived:
            writeInt(&buf, Int32(12))
        
        
        case let .credentialApproved(domain,credentialId):
            writeInt(&buf, Int32(13))
            FfiConverterOptionString.write(domain, into: &buf)
            FfiConverterOptionString.write(credentialId, into: &buf)
            
        
        case let .credentialDenied(domain,credentialId):
            writeInt(&buf, Int32(14))
            FfiConverterOptionString.write(domain, into: &buf)
            FfiConverterOptionString.write(credentialId, into: &buf)
            
        
        case let .reconnectingToSession(fingerprint):
            writeInt(&buf, Int32(15))
            FfiConverterString.write(fingerprint, into: &buf)
            
        
        case let .sessionRefreshed(fingerprint):
            writeInt(&buf, Int32(16))
            FfiConverterString.write(fingerprint, into: &buf)
            
        
        case let .rendezvousResolving(code):
            writeInt(&buf, Int32(17))
            FfiConverterString.write(code, into: &buf)
            
        
        case let .rendezvousResolved(fingerprint):
            writeInt(&buf, Int32(18))
            FfiConverterString.write(fingerprint, into: &buf)
            
        
        case let .pskMode(fingerprint):
            writeInt(&buf, Int32(19))
            FfiConverterString.write(fingerprint, into: &buf)
            
        
        case let .disconnected(reason):
            writeInt(&buf, Int32(20))
            FfiConverterOptionString.write(reason, into: &buf)
            
        
        case let .reconnecting(attempt):
            writeInt(&buf, Int32(21))
            FfiConverterUInt32.write(attempt, into: &buf)
            
        
        case .reconnected:
            writeInt(&buf, Int32(22))
        
        
        case let .error(message,context):
            writeInt(&buf, Int32(23))
            FfiConverterString.write(message, into: &buf)
            FfiConverterOptionString.write(context, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEvent_lift(_ buf: RustBuffer) throws -> FfiEvent {
    return try FfiConverterTypeFfiEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEvent_lower(_ value: FfiEvent) -> RustBuffer {
    return FfiConverterTypeFfiEvent.lower(value)
}



extension FfiEvent: Equatable, Hashable {}




/**
 * FFI-friendly error enum that maps the internal ClientError
 * into 6 categories suitable for cross-language consumption.
 */
public enum RemoteAccessError {

    
    
    case ConnectionFailed(message: String
    )
    case HandshakeFailed(message: String
    )
    case CredentialRequestFailed(message: String
    )
    case SessionError(message: String
    )
    case InvalidArgument(message: String
    )
    case Timeout(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRemoteAccessError: FfiConverterRustBuffer {
    typealias SwiftType = RemoteAccessError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RemoteAccessError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ConnectionFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .HandshakeFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .CredentialRequestFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .SessionError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .InvalidArgument(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Timeout(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RemoteAccessError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ConnectionFailed(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .HandshakeFailed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .CredentialRequestFailed(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .SessionError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidArgument(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Timeout(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension RemoteAccessError: Equatable, Hashable {}

extension RemoteAccessError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




/**
 * Callback interface for persistent connection storage.
 *
 * Implement this to control where cached connections are stored.
 */
public protocol ConnectionStorage : AnyObject {
    
    /**
     * Get a cached connection by hex-encoded fingerprint.
     */
    func get(fingerprintHex: String)  -> FfiStoredConnection?
    
    /**
     * Save a connection (insert or update).
     */
    func save(connection: FfiStoredConnection) throws 
    
    /**
     * Update the last_connected_at timestamp for an existing connection.
     */
    func update(fingerprintHex: String, lastConnectedAt: UInt64) throws 
    
    /**
     * List all cached connections.
     */
    func list()  -> [FfiStoredConnection]
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceConnectionStorage {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceConnectionStorage = UniffiVTableCallbackInterfaceConnectionStorage(
        get: { (
            uniffiHandle: UInt64,
            fingerprintHex: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> FfiStoredConnection? in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceConnectionStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.get(
                     fingerprintHex: try FfiConverterString.lift(fingerprintHex)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionTypeFfiStoredConnection.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        save: { (
            uniffiHandle: UInt64,
            connection: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceConnectionStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.save(
                     connection: try FfiConverterTypeFfiStoredConnection.lift(connection)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeRemoteAccessError.lower
            )
        },
        update: { (
            uniffiHandle: UInt64,
            fingerprintHex: RustBuffer,
            lastConnectedAt: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceConnectionStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.update(
                     fingerprintHex: try FfiConverterString.lift(fingerprintHex),
                     lastConnectedAt: try FfiConverterUInt64.lift(lastConnectedAt)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeRemoteAccessError.lower
            )
        },
        list: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> [FfiStoredConnection] in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceConnectionStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.list(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterSequenceTypeFfiStoredConnection.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceConnectionStorage.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface ConnectionStorage: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitConnectionStorage() {
    uniffi_ap_uniffi_fn_init_callback_vtable_connectionstorage(&UniffiCallbackInterfaceConnectionStorage.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceConnectionStorage {
    fileprivate static var handleMap = UniffiHandleMap<ConnectionStorage>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceConnectionStorage : FfiConverter {
    typealias SwiftType = ConnectionStorage
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Callback interface for handling credential requests from remote devices.
 *
 * Implement this in Python/Kotlin/Swift to serve credentials when a remote
 * device requests them.
 */
public protocol CredentialProvider : AnyObject {
    
    /**
     * Handle a credential request from a remote device.
     *
     * * `query_type` — The type of query: "domain", "id", or "search".
     * * `query_value` — The query value (e.g. "example.com" for domain queries).
     * * `remote_fingerprint` — Hex-encoded fingerprint of the requesting device.
     *
     * Return credential data to approve, or `None` to deny.
     */
    func handleCredentialRequest(queryType: String, queryValue: String, remoteFingerprint: String)  -> FfiCredentialData?
    
    /**
     * Handle fingerprint verification for a new rendezvous connection.
     *
     * * `fingerprint` — The 6-character hex handshake fingerprint.
     * * `remote_identity` — Hex-encoded identity fingerprint of the remote device.
     *
     * Return `true` to accept, `false` to reject.
     */
    func verifyFingerprint(fingerprint: String, remoteIdentity: String)  -> Bool
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceCredentialProvider {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceCredentialProvider = UniffiVTableCallbackInterfaceCredentialProvider(
        handleCredentialRequest: { (
            uniffiHandle: UInt64,
            queryType: RustBuffer,
            queryValue: RustBuffer,
            remoteFingerprint: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> FfiCredentialData? in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCredentialProvider.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.handleCredentialRequest(
                     queryType: try FfiConverterString.lift(queryType),
                     queryValue: try FfiConverterString.lift(queryValue),
                     remoteFingerprint: try FfiConverterString.lift(remoteFingerprint)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionTypeFfiCredentialData.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        verifyFingerprint: { (
            uniffiHandle: UInt64,
            fingerprint: RustBuffer,
            remoteIdentity: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCredentialProvider.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.verifyFingerprint(
                     fingerprint: try FfiConverterString.lift(fingerprint),
                     remoteIdentity: try FfiConverterString.lift(remoteIdentity)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceCredentialProvider.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface CredentialProvider: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitCredentialProvider() {
    uniffi_ap_uniffi_fn_init_callback_vtable_credentialprovider(&UniffiCallbackInterfaceCredentialProvider.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceCredentialProvider {
    fileprivate static var handleMap = UniffiHandleMap<CredentialProvider>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceCredentialProvider : FfiConverter {
    typealias SwiftType = CredentialProvider
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Callback interface for receiving status notifications.
 *
 * Optional — implement to receive events like handshake progress, connection
 * state changes, errors, etc.
 */
public protocol EventHandler : AnyObject {
    
    /**
     * Called when a notification event occurs.
     */
    func onEvent(event: FfiEvent) 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventHandler {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceEventHandler = UniffiVTableCallbackInterfaceEventHandler(
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeFfiEvent.lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceEventHandler.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface EventHandler: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitEventHandler() {
    uniffi_ap_uniffi_fn_init_callback_vtable_eventhandler(&UniffiCallbackInterfaceEventHandler.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceEventHandler {
    fileprivate static var handleMap = UniffiHandleMap<EventHandler>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceEventHandler : FfiConverter {
    typealias SwiftType = EventHandler
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Callback interface for persistent identity storage.
 *
 * Implement this to control where identity keypairs are stored (file, keychain,
 * database, etc.). The bytes are opaque — just store and return them as-is.
 * No CBOR/COSE parsing is needed on the language side.
 */
public protocol IdentityStorage : AnyObject {
    
    /**
     * Load previously saved identity bytes, or None if no identity exists yet.
     */
    func loadIdentity()  -> Data?
    
    /**
     * Save identity bytes for later retrieval.
     */
    func saveIdentity(identityBytes: Data) throws 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceIdentityStorage {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceIdentityStorage = UniffiVTableCallbackInterfaceIdentityStorage(
        loadIdentity: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data? in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceIdentityStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.loadIdentity(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionData.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        saveIdentity: { (
            uniffiHandle: UInt64,
            identityBytes: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceIdentityStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.saveIdentity(
                     identityBytes: try FfiConverterData.lift(identityBytes)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeRemoteAccessError.lower
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceIdentityStorage.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface IdentityStorage: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitIdentityStorage() {
    uniffi_ap_uniffi_fn_init_callback_vtable_identitystorage(&UniffiCallbackInterfaceIdentityStorage.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceIdentityStorage {
    fileprivate static var handleMap = UniffiHandleMap<IdentityStorage>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceIdentityStorage : FfiConverter {
    typealias SwiftType = IdentityStorage
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiCredentialData: FfiConverterRustBuffer {
    typealias SwiftType = FfiCredentialData?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiCredentialData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiCredentialData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiStoredConnection: FfiConverterRustBuffer {
    typealias SwiftType = FfiStoredConnection?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiStoredConnection.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiStoredConnection.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceEventHandler: FfiConverterRustBuffer {
    typealias SwiftType = EventHandler?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceEventHandler.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceEventHandler.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiConnectionInfo: FfiConverterRustBuffer {
    typealias SwiftType = [FfiConnectionInfo]

    public static func write(_ value: [FfiConnectionInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiConnectionInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiConnectionInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiConnectionInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiConnectionInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiStoredConnection: FfiConverterRustBuffer {
    typealias SwiftType = [FfiStoredConnection]

    public static func write(_ value: [FfiStoredConnection], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiStoredConnection.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiStoredConnection] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiStoredConnection]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiStoredConnection.read(from: &buf))
        }
        return seq
    }
}
/**
 * Check whether a token string looks like a PSK token.
 *
 * Returns `true` if the token matches the PSK format
 * (`<64-hex-psk>_<64-hex-fingerprint>`, 129 chars).
 * Useful for consumers to dispatch between `pair_with_psk()` and
 * `pair_with_handshake()`.
 */
public func looksLikePskToken(token: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_ap_uniffi_fn_func_looks_like_psk_token(
        FfiConverterString.lower(token),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ap_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ap_uniffi_checksum_func_looks_like_psk_token() != 8301) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_remoteaccessclient_close() != 10183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_remoteaccessclient_connect() != 26254) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_remoteaccessclient_list_connections() != 44068) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_remoteaccessclient_load_existing_connection() != 43405) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_remoteaccessclient_pair_with_handshake() != 21049) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_remoteaccessclient_pair_with_psk() != 44904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_remoteaccessclient_request_credential() != 35782) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_useraccessclient_close() != 59191) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_useraccessclient_connect() != 22307) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_useraccessclient_get_psk_token() != 35429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_useraccessclient_get_rendezvous_token() != 2825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_constructor_remoteaccessclient_new() != 10779) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_constructor_useraccessclient_new() != 22180) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_connectionstorage_get() != 32546) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_connectionstorage_save() != 12434) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_connectionstorage_update() != 40355) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_connectionstorage_list() != 10980) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_credentialprovider_handle_credential_request() != 39331) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_credentialprovider_verify_fingerprint() != 30418) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_eventhandler_on_event() != 62743) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_identitystorage_load_identity() != 58675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ap_uniffi_checksum_method_identitystorage_save_identity() != 244) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitConnectionStorage()
    uniffiCallbackInitCredentialProvider()
    uniffiCallbackInitEventHandler()
    uniffiCallbackInitIdentityStorage()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all